name: fake_call
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  image_picker: ^0.6.7+22
  contact_picker: ^0.0.2
  flutter_local_notifications: ^4.0.1
  flutter_native_timezone: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: fonts/HelveticaNeue Light.ttf
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf